apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: tasks
            - name: POSTGRES_USER
              value: taskuser
            - name: POSTGRES_PASSWORD
              value: taskpass
          ports:
            - containerPort: 5432
